name: EvaluateSurveySubscriber
on:
  push:
    branches:
      - main
    paths:
      'backend/EvaluateSurveySubscriber/**'
  workflow_dispatch:
  workflow_run:
    workflows: [EvaluateSurveySchema]
    types: [completed]
jobs:
  BuildAndDeploy:
    uses: MichaelDiers/shared-workflows/.github/workflows/dotnet-deploy-google-cloud-function.yaml@main
    with:
      functionName: EvaluateSurveySubscriber 
      projectName: EvaluateSurveySubscriber
      solutionFolder: backend/EvaluateSurveySubscriber
      trigger: pubsub
    secrets:
      gcpCredentialsTest: ${{ secrets.GLOBAL_GCP_CREDENTIALS_TEST }}
      gcpCredentialsStage: ${{ secrets.GLOBAL_GCP_CREDENTIALS_STAGE }}
      gcpCredentialsProd: ${{ secrets.GLOBAL_GCP_CREDENTIALS_PROD }}
      projectIdTest: ${{ secrets.GLOBAL_PROJECT_ID_TEST }}
      projectIdStage: ${{ secrets.GLOBAL_PROJECT_ID_STAGE }}
      projectIdProd: ${{ secrets.GLOBAL_PROJECT_ID_PROD }}
      appSettingsJsonTest: '\{\"Logging\":\{\"LogLevel\":\{\"Microsoft\":\"Information\"\}\},\"ProjectId\": \"${{ secrets.GLOBAL_PROJECT_ID_TEST }}\",\"Environment\": \"Test\",\"SaveSurveyStatusTopicName\": \"${{ secrets.GLOBAL_PUBSUB_TOPIC_SAVE_SURVEY_STATUS }}\",\"SurveyClosedTopicName\": \"${{ secrets.GLOBAL_PUBSUB_TOPIC_SURVEY_CLOSED }}\"\}'
      appSettingsJsonStage: '\{\"Logging\":\{\"LogLevel\":\{\"Microsoft\":\"Error\"\}\},\"ProjectId\": \"${{ secrets.GLOBAL_PROJECT_ID_STAGE }}\",\"Environment\": \"Stage\",\"SaveSurveyStatusTopicName\": \"${{ secrets.GLOBAL_PUBSUB_TOPIC_SAVE_SURVEY_STATUS }}\",\"SurveyClosedTopicName\": \"${{ secrets.GLOBAL_PUBSUB_TOPIC_SURVEY_CLOSED }}\"\}'
      appSettingsJsonProd: '\{\"Logging\":\{\"LogLevel\":\{\"Microsoft\":\"Error\"\}\},\"ProjectId\": \"${{ secrets.GLOBAL_PROJECT_ID_PROD }}\",\"Environment\": \"Prod\",\"SaveSurveyStatusTopicName\": \"${{ secrets.GLOBAL_PUBSUB_TOPIC_SAVE_SURVEY_STATUS }}\",\"SurveyClosedTopicName\": \"${{ secrets.GLOBAL_PUBSUB_TOPIC_SURVEY_CLOSED }}\"\}'
      subTopicName: ${{ secrets.GLOBAL_PUBSUB_TOPIC_EVALUATE_SURVEY }}
