name: schemas/Scehma.InitializeSurvey.yaml
on:
  push:
    branches:
      - main
    paths:
      - 'schemas/InitializeSurveySchema.avro'
      - '.github/workflows/Schema.InitializeSurvey.yaml'
  workflow_dispatch:
jobs:
  createSchemaAndTopic:
    uses: MichaelDiers/shared-workflows/.github/workflows/deploy-google-cloud-pubsub-schema-topic.yaml@main
    with:
      messageEnconding: json
      schemaFile: schemas/InitializeSurveySchema.avro
      schemaType: AVRO
    secrets:
      gcpCredentialsTest: ${{ secrets.GLOBAL_GCP_CREDENTIALS_TEST }}
      gcpCredentialsStage: ${{ secrets.GLOBAL_GCP_CREDENTIALS_STAGE }}
      gcpCredentialsProd: ${{ secrets.GLOBAL_GCP_CREDENTIALS_PROD }}
      projectIdTest: ${{ secrets.GLOBAL_PROJECT_ID_TEST }}
      projectIdStage: ${{ secrets.GLOBAL_PROJECT_ID_STAGE }}
      projectIdProd: ${{ secrets.GLOBAL_PROJECT_ID_PROD }}
      topicName: ${{ secrets.GLOBAL_PUBSUB_TOPIC_INITIALIZE_SURVEY }}