name: BE/SurveyEvaluatorService.yaml
on:
  push:
    branches:
      - main
    paths:
      - 'backend/SurveyEvaluatorService/SurveyEvaluatorService/**'
  workflow_dispatch:
env:
  APP_SETTINGS_JSON: 'backend/SurveyEvaluatorService/SurveyEvaluatorService/appsettings.json'
  CONFIG: Release
  SOURCE_DIR: 'backend/SurveyEvaluatorService/SurveyEvaluatorService'
  ENTRY_POINT: SurveyEvaluatorService.SurveyEvaluatorFunction
  FUNCTION_NAME: SurveyEvaluatorService
  SLN_FILE: 'backend/SurveyEvaluatorService/SurveyEvaluatorService.sln'
  COLLECTION_NAME_SURVEY_RESULTS: ${{ secrets.GLOBAL_SURVEY_RESULTS_COLLECTION_NAME }}
  COLLECTION_NAME_SURVEY_STATUS: ${{ secrets.GLOBAL_SURVEYS_STATUS_COLLECTION_NAME }}
  COLLECTION_NAME_SURVEYS: ${{ secrets.GLOBAL_SURVEYS_COLLECTION_NAME }}
  TOPIC_SEND_MAIL: ${{ secrets.GLOBAL_PUBSUB_TOPIC_SEND_MAIL }}
  TOPIC_STATUS_UPDATE: ${{ secrets.GLOBAL_PUBSUB_TOPIC_SURVEY_STATUS_UPDATE }}
  TEMPLATE_PLAIN_NEWLINE: ${{ secrets.GLOBAL_TEMPLATE_NEWLINE }}
jobs:  
  test:
    runs-on: ubuntu-latest
    environment:
      name: SurveyEvaluatorService-Test
    env:
      GCP_CREDENTIALS: ${{ secrets.GLOBAL_GCP_CREDENTIALS_TEST }}
      PROJECT_ID: ${{ secrets.GLOBAL_PROJECT_ID_TEST }}
      SURVEY_VIEWER_LINK: ${{ secrets.GLOBAL_SURVEY_VIEWER_LINK_TEST }}
      TEMPLATE_HTML_THANK_YOU: ${{ secrets.TEMPLATE_HTML_THANK_YOU }}
      TEMPLATE_HTML_THANK_YOU_ANSWER: ${{ secrets.TEMPLATE_HTML_THANK_YOU_ANSWER }}      
      TEMPLATE_PLAIN_THANK_YOU: ${{ secrets.TEMPLATE_PLAIN_THANK_YOU }}
      TEMPLATE_PLAIN_THANK_YOU_ANSWER: ${{ secrets.TEMPLATE_PLAIN_THANK_YOU_ANSWER }}
      TEMPLATE_THANK_YOU_SUBJECT: ${{ secrets.TEMPLATE_THANK_YOU_SUBJECT }}
      TEMPLATE_HTML_CLOSED_SURVEY: ${{ secrets.TEMPLATE_HTML_CLOSED_SURVEY }}
      TEMPLATE_HTML_CLOSED_SURVEY_ANSWER: ${{ secrets.TEMPLATE_HTML_CLOSED_SURVEY_ANSWER }}
      TEMPLATE_PLAIN_CLOSED_SURVEY: ${{ secrets.TEMPLATE_PLAIN_CLOSED_SURVEY }}
      TEMPLATE_PLAIN_CLOSED_SURVEY_ANSWER: ${{ secrets.TEMPLATE_PLAIN_CLOSED_SURVEY_ANSWER }}
      TEMPLATE_CLOSED_SURVEY_SUBJECT: ${{ secrets.TEMPLATE_CLOSED_SURVEY_SUBJECT }}
      TEMPLATE_NO_ANSWER: ${{ secrets.TEMPLATE_NO_ANSWER }}
    steps:      
      - name: checkout source
        uses: actions/checkout@v2
      - name: configure appsettings.json
        uses: microsoft/variable-substitution@v1
        with:
          files: ${{ env.APP_SETTINGS_JSON }}
        env:          
          ProjectId: ${{ env.PROJECT_ID }}
          CollectionNameStatus: ${{ env.COLLECTION_NAME_SURVEY_STATUS }}
          CollectionNameSurveys: ${{ env.COLLECTION_NAME_SURVEYS }}
          TopicNameSendMail: ${{ env.TOPIC_SEND_MAIL }}
          SurveyViewerUrl: ${{ env.SURVEY_VIEWER_LINK }}
          TemplateHtmlThankYou: ${{ env.TEMPLATE_HTML_THANK_YOU }}
          TemplateHtmlThankYouAnswer: ${{ env.TEMPLATE_HTML_THANK_YOU_ANSWER }}
          TemplatePlainNewline: ${{ env.TEMPLATE_PLAIN_NEWLINE }}
          TemplatePlainThankYou: ${{ env.TEMPLATE_PLAIN_THANK_YOU }}
          TemplatePlainThankYouAnswer: ${{ env.TEMPLATE_PLAIN_THANK_YOU_ANSWER }}
          TemplateThankYouSubject: ${{ env.TEMPLATE_THANK_YOU_SUBJECT }}
          CollectionNameResults: ${{ env.COLLECTION_NAME_SURVEY_RESULTS }}
          TopicNameStatusUpdate: ${{ env.TOPIC_STATUS_UPDATE }}
          TemplateHtmlClosedSurvey: ${{ env.TEMPLATE_HTML_CLOSED_SURVEY }}
          TemplateHtmlClosedSurveyAnswer: ${{ env.TEMPLATE_HTML_CLOSED_SURVEY_ANSWER }}
          TemplatePlainClosedSurvey: ${{ env.TEMPLATE_PLAIN_CLOSED_SURVEY }}
          TemplatePlainClosedSurveyAnswer: ${{ env.TEMPLATE_PLAIN_CLOSED_SURVEY_ANSWER }}
          TemplateClosedSurveySubject: ${{ env.TEMPLATE_CLOSED_SURVEY_SUBJECT }}
          TemplateNoAnswer: ${{ env.TEMPLATE_NO_ANSWER }}
      - name: use .net core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: build
        run: dotnet build ${{ env.SLN_FILE }} --configuration "${{ env.CONFIG }}"
      - name: test
        run: dotnet test ${{ env.SLN_FILE }} --configuration "${{ env.CONFIG }}" --no-build
      - name: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ env.GCP_CREDENTIALS }}'
      - name: deploy
        uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: ${{ env.FUNCTION_NAME }}
          runtime: dotnet3          
          project_id: ${{ env.PROJECT_ID }}          
          source_dir: ${{ env.SOURCE_DIR }}
          entry_point: ${{ env.ENTRY_POINT }}
          event_trigger_type: providers/cloud.firestore/eventTypes/document.create
          event_trigger_resource: projects/${{ env.PROJECT_ID }}/databases/(default)/documents/${{ env.COLLECTION_NAME_SURVEY_RESULTS }}/{result}